### ISSUE TITLE
Add a whitelist check

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gcfa-ui#25]
We must check user's Proof-of-Liveness before we allow him to click on the 'Deposit' button.

**Comment by Shloyem** [comment]
We can do the same like in depositFor
`IIdentity(nameService.getAddress("IDENTITY")).isWhitelisted(msg.sender)`

If we call the [NameService contract](https://celoscan.io/address/0x0f5db7a64a6a64052693676ca898ec7f7a94ff4e#readProxyContract) you sent, with getAddress("IDENTITY")


![Image](https://github.com/w3hc/gcfa-ui/assets/39220943/b7b2cffe-29b9-4d3d-968b-25d6e98ed58a)

We get the [Identity contract](https://celoscan.io/address/0xC361A6E67822a0EDc17D899227dd9FC50BD62F42#readProxyContract), that we call for isWhiteListed


![Image](https://github.com/w3hc/gcfa-ui/assets/39220943/74d4f56b-3029-47b8-ad57-baac814982b3)

**Comment by julienbrg** [comment]
Oh wow yes, that's chrystal clear. Thank you @Shloyem!
